services:
  web:
    image: php:8.3.7-cli
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8080
    depends_on:
      - postgres
      - composer
  postgres:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: appuser
      POSTGRES_DB: app
      POSTGRES_PASSWORD: apppass
  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: composer install