name: CI-composer-version

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"