name: CI-composer-version

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.26
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}